local app_render = require("ld48.app.render")

go.property("color", vmath.vector3(1, 1, 1))

function init(self)
end

function final(self)
end

function update(self, dt)
    local tint = vmath.vector4(self.color.x, self.color.y, self.color.z, app_render.holo_tint and 0.65 or 0.75)
    go.set("#holo", "tint", tint)
    -- go.set("#label", "color.w", app_render.holo_tint and 0.5 or 0.75)
end

function on_message(self, message_id, message, sender)
end
